version: '3.8'

services:
  app:
    build: .
    container_name: my_node_app
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
